apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 2048-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yugandharreddy23/devops-eks-portfolio.git
    targetRevision: main
    path: k8s/2048-game/2048-game
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
