name: destroy-eks-argocd

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_cluster_name: devops-eks-portfolio-cluster
      TF_VAR_region: us-west-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Recreate Terraform Backend Config
        run: |
          BUCKET_NAME=terraform-backend-${{ github.run_id }}
          echo "bucket=\"$BUCKET_NAME\"" > ./terraform/backend-config.auto.tfvars
          echo "key=\"eks/terraform.tfstate\"" >> ./terraform/backend-config.auto.tfvars
          echo "region=\"us-west-1\"" >> ./terraform/backend-config.auto.tfvars

      - name: Terraform Init with Dynamic Backend
        working-directory: ./terraform
        run: terraform init -backend-config=backend-config.auto.tfvars


      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve

      - name: Delete Terraform S3 Backend Bucket
        run: |
          BUCKET_NAME=$(awk -F '"' '/bucket/ {print $2}' ./terraform/backend-config.auto.tfvars)
          aws s3 rb s3://$BUCKET_NAME --force || true